# Project: Simple Calc
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "Simple\ Calc.o"
LINKOBJ  = "Simple Calc.o"
LIBS     = -L"C:/Users/INTEL/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Users/INTEL/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/INTEL/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/INTEL/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/INTEL/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Users/INTEL/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/INTEL/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/INTEL/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Users/INTEL/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = "Simple Calc.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = C:\Users\INTEL\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"Simple\ Calc.o": Simple\ Calc.c
	$(CPP) -c "Simple Calc.c" -o "Simple Calc.o" $(CXXFLAGS)
