# Project: Project3
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "Odd\ or\ even.o"
LINKOBJ  = "Odd or even.o"
LIBS     = -L"C:/Users/INTEL/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Users/INTEL/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/INTEL/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/INTEL/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/INTEL/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Users/INTEL/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/INTEL/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/INTEL/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Users/INTEL/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = "Odd or even.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = C:\Users\INTEL\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

"Odd\ or\ even.o": Odd\ or\ even.c
	$(CC) -c "Odd or even.c" -o "Odd or even.o" $(CFLAGS)
